config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  
  namespace :admins_backoffice do
    get 'welcome/index' # Deshboard
    resources :students
    resources :highlights, only: :index
    resources :admins   # Admins
    resources :subjects # Assuntos
    resources :questions # Perguntas
  end
  devise_for :admins
  
  get 'inicio', to: 'admins_backoffice/admins#index'
  
  root to: 'admins_backoffice/admins#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
  paginates_per 10
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]
  
  def index
    @admins = Admin.all.page(params[:page])
  end  
  
  def new
    @admin = Admin.new
  end
  
  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: 'Usuário cadastrado com sucessso!'
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    params_admin 

    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: 'Usuário atualizado com sucessso!'
    else
      render :edit
    end
  end
  
  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice: 'Usuário excluído com sucesso!'
    else
      render :index
    end
  end

  private
  
  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
  
  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
  
  def set_admin
    @admin = Admin.find(params[:id])
  end  
end

app/controllers/admins_backoffice/highlights_controller.rb
class AdminsBackoffice::HighlightsController < AdminsBackofficeController
  def index
    @students_highlights = Student.all
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:new, :edit]

  def index
    @questions = Question.includes(:subject)
                         .order(:id)
                         .page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if  @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update    
    if  @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if  @question.destroy
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end

  private
  
  def params_question
    params.require(:question).permit(:description, :subject_id,
        answers_attributes: [:id, :description, :correct, :_destroy])
  end

  def set_question
    @question = Question.find(params[:id])
  end  
  
  def get_subjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/students_controller.rb
class AdminsBackoffice::StudentsController < AdminsBackofficeController
  before_action :set_student, only: %i[ show edit update destroy ]

  def index
    @students = Student.all.page(params[:page])
  end  

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)
    if @student.save
      redirect_to admins_backoffice_students_path, notice: 'Aluno cadastrado com sucessso!'
    else
      render :new
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    student_params

    if @student.update(student_params)
      redirect_to admins_backoffice_students_path, notice: 'Aluno atualizado com sucessso!'
    else
      render :edit
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    if @student.destroy
      redirect_to admins_backoffice_students_path, notice: 'Aluno excluído com sucesso!'
    else
      render :index
    end
  end

  private

  def student_params
    params.require(:student).permit(:student_name, :school_name, :teacher_name)
  end

  def set_student
    @student = Student.find(params[:id])
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]
  
  def index
    @subjects = Subject.all.order(:description).page(params[:page])
  end  
  
  def new
    @subject = Subject.new
  end
  
  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice: 'Assunto/Área cadastrado com sucessso!'
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    params_subject 

    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice: 'Assunto/Área atualizado com sucessso!'
    else
      render :edit
    end
  end
  
  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área excluído com sucesso!"
    else
      render :index
    end
  end

  private
  
  def params_subject
    params.require(:subject).permit(:description)
  end
  
  def set_subject
    @subject = Subject.find(params[:id])
  end  
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
  def translate_attribute(object = nil, method = nil)
    (object && method) ? object.model.human_attribute_name(method) : "Informe os parâmetros corretamente!"
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admins_backoffice/students/edit.html.erb
<%= render partial: 'admins_backoffice/students/shared/form',
           locals: { action_message: 'Editando' }%>

app/views/admins_backoffice/students/index.html.erb
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><%="Listando Alunos" %></h1>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
      <thead>
          <tr>
              <th>Nome</th>
              <th>Escola</th>
              <th>Professor</th>
              <th>
                  <%= link_to new_admins_backoffice_student_path, class:"btn btn-success btn-circle btn-sm" do %>
                  <i class="fa fa-plus"></i>
                  <%end%>
              </th>
          </tr>
      </thead>
      <tbody>
          <% @students.each do |students| %>
          <tr>
              <td><%= students.student_name %></td>
              <td><%= students.school_name %></td>
              <td><%= students.teacher_name %></td>
              <td style="width: 100px">
                
                <%= link_to edit_admins_backoffice_student_path(students), class:"btn btn-primary btn-circle btn-sm" do %>
                <i class="fa fa-edit"></i>
                <%end%>
                
                <%= link_to admins_backoffice_student_path(students), method: :delete, 
                  class:"btn btn-danger btn-circle btn-sm", 
                  data: { confirm: t('messages.confirm_with', item: students.student_name.truncate(30)) } do %>
                  
                <i class="fa fa-minus"></i>
                <%end%>
              
              </td>
          </tr>
          <% end %>
      </tbody>
  </table>
    <div class="text-center"> 
      <%= paginate @students %>
    </div>
</div>

app/views/admins_backoffice/students/new.html.erb
<%= render partial: 'admins_backoffice/students/shared/form',
           locals: { action_message: 'Novo' }%>