config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
    get 'search', to: 'search#questions'
    get 'subject/:subject_id/:subject', to: 'search#subject', as: 'search_subject'
    post 'answer', to: 'answer#question'
  end
  
  namespace :admins_backoffice do
    get 'welcome/index' # Deshboard
    resources :students
    resources :highlights, only: :index
    resources :admins   # Admins
    resources :subjects # Assuntos
    resources :questions # Perguntas
  end
  devise_for :admins
  
  get 'inicio', to: 'admins_backoffice/admins#index'
  
  root to: 'admins_backoffice/admins#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/site/answer_controller.rb
class Site::AnswerController < SiteController
  def question 
    @answer = Answer.find(params[:answer_id])
  end
end

app/controllers/site/search_controller.rb
class Site::SearchController < SiteController
  def questions
     @questions = Question.search(params[:page], params[:term])
  end
  
  def subject
     @questions = Question._search_subject_(params[:page], params[:subject_id])
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
    @questions = Question.last_questions(params[:page])
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/helpers/site/answer_helper.rb
module Site::AnswerHelper
end

app/helpers/site/search_helper.rb
module Site::SearchHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
  def msg_jumbotron
    case params[:action]
    when 'index'
      "Últimas perguntas cadastradas..."
    when 'question'
      "Resultados para o termo \"#{params[:term]}\"..."
    when 'subject'
      "Mostrando questões para o assunto \"#{params[:subject]}\"..."
    end
  end
end

app/views/site/shared/_questions.html.erb
</br>
<main role="main">
  <div class="jumbotron">
   <h3> <%= msg_jumbotron %> </h3>
  </div>
</main>

<% @questions.each do |question| %>
  <%= form_with url: site_answer_path do |form| %>
    <div class="card">
      <h3 class="card-header"> 
        <span class="btn btn-primary btn-sm">
          <%= link_to question.subject.description, site_search_subject_path(question.subject_id, question.subject.description), style:"color: white;" %>
        </span>
        <%= question.description %>
      </h3>
      <div class="card-body">
        <ul>
          <% question.answers.each do |answer| %>
            <li style="list-style:none;" >
              <div class="radio">
                <label>
                  <%= radio_button_tag 'answer_id', answer.id %>
                  <%= answer.description %>
                </label>
              </div>
            </li> 
          <% end %>
          <li style="list-style:none;">
            <%= form.submit "Responder", class:"btn btn-secondary", id: "submit_#{question.id}" %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
<% end %>

<hr>
<div class="text-center"> 
    <%= paginate @questions %>
</div>